stages:
  - build
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'production'
  PROJECT_DIR: '/www/wwwroot/sahabatkebaikan-frontend-production'
  NEXT_PUBLIC_BASE_URL: 'https://api.sahabatkebaikan.org'
  NEXT_PUBLIC_WEB_URL: 'https://sahabatkebaikan.org'
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID: 795476387991328
  NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyBCT7iD1ZfXKQnVCoKFZqoRVkvzfaZ16K8'
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'sahabatkebaikan-org.firebaseapp.com'
  NEXT_PUBLIC_DATABASE_URL: 'https://sahabatkebaikan-org-default-rtdb.firebaseio.com/'
  NEXT_PUBLIC_PROJECT_ID: 'sahabatkebaikan-org'
  NEXT_PUBLIC_STORAGE_BUCKET: 'sahabatkebaikan-org.appspot.com'
  NEXT_PUBLIC_MESSAGING_SENDER_ID: '416643031057'
  NEXT_PUBLIC_APP_ID: '1:416643031057:web:f07302f48fb44db261d1b0'
  NEXT_PUBLIC_MEASUREMENT_ID: 'G-M0N2RFV6VN'

build_production:
  stage: build
  tags:
    - prod-env-sahabatkebaikan
  script:
    # Only copy changed files to project folder
    - cp -r -u . $PROJECT_DIR
    - cd $PROJECT_DIR
    - yarn install
    - yarn run build
  only:
    - master

deploy_production:
  stage: deploy
  tags:
    - prod-env-sahabatkebaikan
  script:
    - cd $PROJECT_DIR
    - pm2 delete ecosystem.config.js --only sahabatkebaikan-production
    - pm2 restart ecosystem.config.js --only sahabatkebaikan-production
  only:
    - master
